movie/movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/movieapp/urls.py
from . import views
from django.urls import path, include
app_name = 'movieapp'


urlpatterns = [
    path('', views.home, name='home'),

    path('movies/<int:id>', views.detail, name='Detail'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),

    path('form', views.form, name='forms'),
]

movie/movieapp/models.py
from django.db import models


# Create your models here.
class Film(models.Model):
    name = models.CharField(max_length=111)
    year = models.IntegerField()
    image = models.ImageField(upload_to='media')
    description = models.CharField(max_length=500, default='No description available')


    def __str__(self):
        return self.name

movie/movieapp/forms.py

from django import forms

from .models import Film


class MovieForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ['name', 'year', 'image', 'description']



movie/movieapp/views.py
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Film


# Create your views here.
def home(request):
    a = Film.objects.all()
    return render(request, 'home.html', {'obj': a})


def detail(request, id):
    mo = Film.objects.get(id=id)
    return render(request, 'details.html', {'mo': mo})


def form(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        year = request.POST.get('year', )
        img = request.FILES['image']
        desc = request.FILES['description']

        m = Film(name=name, year=year, image=img, description=desc)
        m.save()
        return redirect('/')
    return render(request, 'forms.html')


def update(request, id):
    c = Film.objects.get(id=id)
    forms = MovieForm(request.POST or None, request.FILES, instance=c)
    if forms.is_valid():
        forms.save()
        return redirect('/')
    else:
        forms = MovieForm(instance=c)
        return render(request, 'update.html', {'forms': forms})

def delete(request, id):
    if request.method == 'POST':
        c = Film.objects.get(id=id)
        c.delete()
        return redirect('/')
    return render(request, 'delete.html')

movie/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="static/style.css">
</head>
<body style="background-color:Black; padding:15px;">
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <h3>MoviesHub</h3>
  </a>
    <a class="navbar-brand" href="{% url 'movieapp:forms' %}">
    <h3>Add Movies</h3>
  </a>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

movie/templates/delete.html
{% extends 'base.html' %}

{% block body %}
<form method="post">
  {% csrf_token %}
  confirm
  <input type="submit" value="ok">
</form>
{% endblock %}

movie/templates/details.html
{% extends 'base.html' %}


{% block body %}

<div class="container">
    <div class="row" style="padding:15px;">
        <div class="col-md-6">
            <img src="{{mo.image.url}}" style="height:300px;">
        </div>
        <div>
            <h3 style="padding-left:233px; margin:25px;">{{mo.name}}</h3><br>
            <h4 style="padding-left:233px; margin:25px;">{{mo.year}}</h4>
            <h4 style="padding-left:233px; margin:25px;">{{mo.description}}</h4>
        </div>
    </div>
</div>
<a href="{% url 'movieapp:update' mo.id %}">
  <button>update</button>
</a>
<a href="{% url 'movieapp:update' mo.id %}">
  <button>delete</button>
</a>


{% endblock %}

movie/templates/forms.html
{% extends 'base.html' %}

{% block body %}

<form method="post" action="form"  enctype="multipart/form-data">
  {% csrf_token %}

  <input type="text" id="name" name="name" required><br><br>
  <input type="text" id="description" name="description" required><br><br>

  <input type="number" id="year" name="year" required><br><br>


  <input type="file" id="image" name="image"><br><br>

  <input type="submit" value="Submit">
</form>
{% endblock %}

movie/templates/home.html
{% extends 'base.html' %}


{% block body %}

<div class="row">
  <div class="col-md-3 ">
    <div class="card text-white bg-primary mb-3" style="max-width: 18rem; margin-top:73px; margin-left:49px">
      <div class="card-header">Header</div>
      <div class="card-body">
        <h5 class="card-title">Primary card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
    </div>
    
    <!-- add more cards here -->
  </div>

<div class="col-md-9" style="padding:15px; ">
  <div class="row" style="padding:15px; margin:20px;">
    {% for i in obj %}
    <div class="col-md-4">
      <div class="card" style="position: relative; width: 20rem; height: 400px; margin:17px">
        <img class="card-img-top" src="{{i.image.url}}" style="height:100%; width:100%; object-fit: cover;">
        <div class="card-body" style="position: absolute; bottom: 0; left: 0; right: 0; background-color: rgba(0, 0, 0, 0.6);">
          <h5 class="card-title" style="margin-bottom: 0;">
            <a href="{% url 'movieapp:Detail' i.id %}">
              <button class="btn btn-primary" style="background-color: aqua; border:none; font-weight:bold; padding: 8px 20px; border-radius: 20px; transition: all 0.2s;">
                {{i.name}}
              </button>
            </a>
          </h5>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>





{% endblock %}

























<!--<div class="card text-white bg-primary mb-3" style="max-width: 18rem;">-->
<!--  <div class="card-header">Header</div>-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">Primary card title</h5>-->
<!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">-->
<!--  <div class="card-header">Header</div>-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">Secondary card title</h5>-->
<!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="card text-white bg-success mb-3" style="max-width: 18rem;">-->
<!--  <div class="card-header">Header</div>-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">Success card title</h5>-->
<!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="card text-white bg-danger mb-3" style="max-width: 18rem;">-->
<!--  <div class="card-header">Header</div>-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">Danger card title</h5>-->
<!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="card text-white bg-warning mb-3" style="max-width: 18rem;">-->
<!--  <div class="card-header">Header</div>-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">Warning card title</h5>-->
<!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="card text-white bg-info mb-3" style="max-width: 18rem;">-->
<!--  <div class="card-header">Header</div>-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">Info card title</h5>-->
<!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="card bg-light mb-3" style="max-width: 18rem;">-->
<!--  <div class="card-header">Header</div>-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">Light card title</h5>-->
<!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">-->
<!--  <div class="card-header">Header</div>-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">Dark card title</h5>-->
<!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--  </div>-->
<!--</div>-->


<!--<div class="container">-->
<!--    <div class="row" style="padding:15px;">-->
<!--        {% for i in obj %}-->
<!--        <div class="col-md-4">-->

<!--<div class="card" style="width: 16rem;">-->
<!--<img class="card-img-top" src="{{i.image.url}}" style="height:155px">-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title"><a href="{% url 'movieapp:Detail' i.id %}">{{i.name}}</a></h5>-->

<!--  </div>-->
<!--</div>-->
<!--        </div>-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--</div>-->































movie/templates/update.html
{% extends 'base.html' %}

{% block body %}
<h1>Update</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ forms.as_p }}
  <button class="btn btn-primary" type="submit">update</button>

</form>
{% endblock %}